---
sensor:
  - platform: adc
    id: tamper_raw
    pin: ${tamper_pin}
    attenuation: 11db
    update_interval: ${adc_read_time}
    unit_of_measurement: ''
    device_class: ''
    raw: true
    on_value:
      - binary_sensor.template.publish:
          id: tamper_state
          state: !lambda |-
             return (x < ${tamper_ok_value} - 150 || x > ${tamper_ok_value} + 150);

binary_sensor:
  - platform: template
    device_class: tamper
    id: tamper_state
    name: ${friendly_name} Tamper
