---
substitutions:
  name: ble-tracker-garage
  friendly_name: BLE Tracker Garage
  wifi_reboot_timeout: 5min
  ip: "10.6.6."

packages:
  common: !include modules/common-32-ble-idf.yaml

  kayas-room-thermometer: !include modules/xiaomi/temperature-kayas-room.yaml
  taikis-room-thermometer: !include modules/xiaomi/temperature-taikis-room.yaml
  garage-thermometer: !include modules/xiaomi/temperature-garage.yaml
  roof_space-thermometer: !include modules/xiaomi/temperature-roof-space.yaml
  office-thermometer: !include modules/xiaomi/temperature-office.yaml

  # hallway-motion: !include modules/xiaomi/motion-hallway.yaml

  gpio0: !include modules/gpio0.yaml

light:
  - platform: status_led
    pin: GPIO2
    name: "${friendly_name} LED"
    effects:
      - strobe:
