---
substitutions:
  name: ble-tracker-lounge
  friendly_name: BLE Tracker Lounge
  wifi_reboot_timeout: 5min
  ip: "10.6.6.115"

packages:
  common: !include modules/common-32-ble.yaml

  lounge-thermometer: !include modules/xiaomi/temperature-lounge.yaml
  master-room-thermometer: !include modules/xiaomi/temperature-master-room.yaml
  ensuite-thermometer: !include modules/xiaomi/temperature-ensuite.yaml
  kitchen-thermometer: !include modules/xiaomi/temperature-kitchen.yaml
  bathroom-thermometer: !include modules/xiaomi/temperature-bathroom.yaml
  hwc-thermometer: !include modules/xiaomi/temperature-hwc.yaml

  gpio0: !include modules/gpio0.yaml

light:
  - platform: status_led
    pin: GPIO2
    name: "${friendly_name} LED"
    effects:
      - strobe:
