substitutions:
  devicename: ensuite-switch
  friendly_name: Ensuite
  wifi_reboot_timeout: 5min

packages:
  common: !include modules/common.yaml
  switch: !include modules/athom-sw03-bathroom-switch.yml

logger:
  baud_rate: 0
