---
substitutions:
  name: taikis-fan
  friendly_name: Taiki's Fan
  fan_name: Taiki
  ip: '10.6.6.'
  wifi_reboot_timeout: 5min

packages:
  fan: !include modules/devices/kogan-turbo-fan.yaml

logger:
  baud_rate: 0
