# this config is the original working interlock config.
# An additional switch is presented to HA. Turning this switch on
# will result in power being supplied to the attached fixture, and
# HA commands will be used to control the smart fixture.
---
binary_sensor:
  - platform: gpio
    pin:
      inverted: true
      number: 13
    name: '${friendly_name} Button'
    internal: true
    on_multi_click: !include: on-multi-click.yaml

globals:
  - id: smartbulbs_latch
    type: bool
    restore_value: no
    initial_value: "false"

switch:
  - name: '${friendly_name} Smart Bulbs'
    platform: template
    id: sw_relay_mode
    device_class: "switch"
    entity_category: "config"
    lambda: |-
      if (id(smartbulbs_latch)) {
        return true;
      } else {
        return false;
      }      
    turn_on_action:
      - globals.set:
          id: smartbulbs_latch
          value: "true"
      - switch.turn_on: 'switch1'
    turn_off_action:
      - globals.set:
          id: smartbulbs_latch
          value: "false"
      - switch.turn_off: 'switch1'
  - platform: template
    id: logicswitch
    name: ${friendly_name} Switch
    optimistic: true
    restore_state: yes
    on_turn_on:
      then:
        - light.turn_on: 
            id: indicator
            effect: "None"
            brightness: 100%
        - if:
            condition:
              - api.connected:
              - lambda: 'return id(smartbulbs_latch);'
            then:
              - homeassistant.event:
                  event: esphome.switch
                  data:
                    device: ${name}
                    action: 'on'
            else: # If HA can't be reached, then
              - switch.turn_on: 'switch1'
    on_turn_off:
      then:
        - light.turn_off: indicator
        - if:
            condition:
            - api.connected:
            - lambda: 'return id(smartbulbs_latch);'
            then:
              - homeassistant.event:
                  event: esphome.switch
                  data:
                    device: ${name}
                    action: 'off'
            else: # If HA can't be reached, then
            - switch.turn_off: 'switch1'
  - platform: output
    id: switch1
    output: relay
    #name: ${friendly_name} Status
    restore_mode: RESTORE_DEFAULT_OFF
    internal: true

light:
  - platform: status_led
    id: errorled
    pin:
      number: GPIO05
      inverted: True
  - platform: monochromatic
    name: "${friendly_name} Indicator"
    id: indicator
    output: pwm
    default_transition_length: 500ms
    disabled_by_default: true
    effects:
      - pulse:
          transition_length: 0.5s
          update_interval: 0.5s

output:
  - platform: esp8266_pwm
    pin: GPIO04
    id: pwm
    frequency: 300 Hz
    min_power: 10%
    inverted: true
  - platform: gpio
    pin: GPIO12
    id: relay
    inverted: false
