xiaomi_rtcgq02lm:
  - id: motion_hallway
    bindkey: '8f029cadbd87702e2a7f41c68a64b616'
    mac_address: '54:EF:44:E3:25:25'

binary_sensor:
  - platform: xiaomi_rtcgq02lm
    id: motion_hallway
    motion:
      name: Hallway Motion
    light:
      name: Hallway Light
    button:
      name: Hallway Motion Button
      disabled_by_default: true

sensor:
  - platform: xiaomi_rtcgq02lm
    id: motion_hallway
    battery_level:
      name: Hallway Motion Battery Level
